databases:
  - name: simple_chatroom
    databaseName: simple_chatroom_91pr
    user: simple_chatroom
    plan: free

services:
  - type: web
    name: api-simple-chatroom
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: simple_chatroom_91pr
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
